onramp:
  - id: rest
    type: rest
    config:
      link: "/pipeline/main/{instance}/to-onramp"
      host: 0.0.0.0
      port: 9139
      resources:
        - path: /
          allow:
            - method: GET
              status_code: 204

pipeline:
  - id: main
    interface:
      inputs:
        - in
        - from-offramp
      outputs:
        - out
        - error
        - to-onramp
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            let $endpoint = "http://localhost:8139{event.path}";
            event
      - id: response-processing
        op: runtime::tremor
        config:
          script: |
            {"response": event}
    links:
      in: [ runtime ]
      runtime: [ out ]
      runtime/error: [ error ]

      #from-offramp: [ to-onramp ]
      from-offramp: [ response-processing ]
      response-processing: [ to-onramp ]
      response-processing/error: [ error ]

offramp:
  - id: upstream
    type: rest
    config:
      link: "/pipeline/main/{instance}/from-offramp"
      endpoints:
        # TODO flexible endpoints/methods
        #- http://localhost:8139/snot
        - http://localhost:8139/hello
      #put: true
      #headers:
      #  "Client": "Tremor"

binding:
  - id: default
    links:
      '/onramp/rest/{instance}/out': [ '/pipeline/main/{instance}/in' ]

      '/pipeline/main/{instance}/out': [
        '/offramp/upstream/{instance}/in',
        #'/offramp/system::stdout/system/in' # for debugging
      ]

      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/system/in' ]

      # for debugging
      '/pipeline/main/{instance}/to-onramp': [ '/offramp/system::stdout/system/in' ]

      # tremor metrics
      #'/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]
mapping:
  /binding/default/01:
    instance: '01'
